### ISSUE TITLE
CSS grid not supported when exporting to PDF.

### ISSUE THREAD

**Issue by chubby1968** [oatear/cider#31]
I have a card with the following grid as shown in Thumbnails in the editor:

![image](https://user-images.githubusercontent.com/66424852/177354340-ff4fc5ca-8dda-47b7-9a83-23c06b233a6f.png)

In Export Preview it looks fine, but after exporting to PDF I get:

![image](https://user-images.githubusercontent.com/66424852/177354512-cbbfde1d-8744-4566-922f-72f26f1b4ba1.png)

CSS used:

```css
.card {
    width: 765px;                                   /* Width:  2.55" * 300 DPI */
    height: 1050px;                                 /* Height: 3.50" * 300 DPI */
    text-align: center;
    display: flex;
    flex-direction: column;
    border: 45px solid hsl(0, 0%, 10%);
    color: hsl(0, 0%, 10%);
    font-weight: 600;
    font-size: 50px;
}
.card .content {
    flex: 1;
    display: grid;
    grid: 33% 33% 33% / 1fr 1fr;
    grid-auto-flow: column;
    width: 100%;
    height: 50%;

}
.content div {
    border: 5px solid gray;
    display: grid;
    grid: 100% / 40% 60%;
}
.content img {
    width: 100%;
    height: 90%;
    margin: auto 0;
    object-fit: contain;
}
.content p {
    display: inline-block;
    padding: 0;
    margin: auto 0;
    font-weight: 6000;
    font-size: 70px;
}
```
